# Features and Labels
Features are inividual measurable properties that you will be using to make predictions about you labels.    
    
e.g. You are trying to design a model that will be able to predict whether you will like a paritcular kind of cuisine kwɪˈzin   
The label is a Yes or No.    
The features here could be things like Sweetness, Spicynes, Tangness 气味 [tæŋ]    
    
we hvae to make sure that they are represented in a way that doesn't skew one feature over another, in other words it's usually a good idea to normalize or standize your features.

# Train/Test Split in sklearn
http://scikit-learn.org/0.17/modules/cross_validation.html


In [1]:
# cross-validation: evaluating estimator performance
#overfitting: a model would have a perfect score but would fail to predict anything useful on yet-unseen data.

# a test set: x_test, y_test

# In scikit-learn a random split into training and test sets can be quickly computed with the 
# train_test_split  helper function.


In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [5]:
iris = datasets.load_iris()
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [17]:
iris.data[0:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [19]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
x_train.data.shape, y_train.data.shape

((90, 4), (90,))

In [26]:
x_test.data.shape, y_test.data.shape

((60, 4), (60,))

In [28]:
clf = svm.SVC(kernel = 'linear', C=1).fit(x_train, y_train)
clf.score(x_test,y_test)

0.96666666666666667

# KFold

K-Folds cross-validator     

Provides train/test indices to split data in train/test sets.    
Split dataset into k consecutive folds without suffling by default.    

Each fold is then used once as validation while the k-1 remaining folds form the training set.


In [29]:
from sklearn.model_selection import KFold


In [32]:
X = np.array([[1,2],[3,4],[1,2],[3,4]])
Y = np.array([1,2,3,4])

In [33]:
kf = KFold(n_splits=2)

In [49]:
kf.get_n_splits(X)

2

In [50]:
print(kf)

KFold(n_splits=2, random_state=None, shuffle=False)


In [51]:
indexes = kf.split(X)
indexes

<generator object _BaseKFold.split at 0x1a10de76d0>

In [52]:
for train_index, test_index in indexes:
    print('TRAIN:', train_index, 'TEST:', test_index)
    x_train, x_test = X[train_index],X[test_index]
    y_train, y_test = Y[train_index],Y[test_index]

TRAIN: [2 3] TEST: [0 1]
TRAIN: [0 1] TEST: [2 3]


In [53]:
x_train


array([[1, 2],
       [3, 4]])

In [57]:
x_test

array([[1, 2],
       [3, 4]])

In [55]:
y_train

array([1, 2])

In [56]:
y_test

array([3, 4])

In [58]:
#X = np.array([[1,2],[3,4],[1,2],[3,4]])
#Y = np.array([1,2,3,4])

# GridSearchCV

In [59]:
# GridSearchCV implements a 'fit' and a 'score' method.
# it also implements 'predict', 'predict_proba','decision_function','transform' and 'inverse_transform' if they are implemented in the estimator used.

#the parameters of the estimator used to apply thse methods are optimized by cross-validated grid-search
#over a parameter grid.


In [60]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [61]:
iris = datasets.load_iris()
parameters = {'kernel':('linear', 'rbf'), 'C':[1,10]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)

In [62]:
clf.fit(iris.data, iris.target)

GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'kernel': ('linear', 'rbf'), 'C': [1, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)