# Questions we might be able to answer

In [1]:
# 1 what variables are related to subway ridership?
# - which stations have the most riders?
# - What are the ridership patterns overtime?
# - how does the weather affect ridership?

# 2 What patterns can I find in the weather?
# - Is the temperature rising throught the month?
# - How does weather vary across the city?

In [2]:
## 2D data
#python: List of lists
#Numpy:2D array
#Pandas: DataFrame
# 2D array, as opposed to array of arrays:
# More memory efficient
#Accessing elements is a bit different a[1,3], rather than a[1][3]
# mean(),std(),etc operate on entire array.

# more :https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray


In [29]:
import numpy as np

In [4]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])



In [5]:
print(ridership[1, 3])
print(ridership[1:3, 3:5])
print(ridership[1, :])

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [6]:
print( ridership[0, :] + ridership[1, :] )
print( ridership[:, 0] + ridership[:, 1] )

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print( a + b )

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [8]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [9]:
#solution by ghwan

def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to 
    find the station with the maximum riders on the first day, then 
    return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    
    ridership_first_day = ridership[0,:]
    print(ridership_first_day)
    station_index_max_first_day = ridership_first_day.argmax()
    print(station_index_max_first_day)
    
    ridership_station_max_first_day = ridership[:, station_index_max_first_day]
    print(ridership_station_max_first_day)
    
    mean_for_max = ridership_station_max_first_day.mean()
    
    overall_mean = ridership.mean()
    
    return (overall_mean, mean_for_max)

In [10]:
mean_riders_for_max_station(ridership)

[0 0 2 5 0]
3
[   5 2328 6461 4787 4477 4979  496   27 4174 4665]


(2342.5999999999999, 3239.9000000000001)

## NumPy axis argument

In [11]:
a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
print( a.sum() )
print(a.sum(axis=0))
print(a.sum(axis=1) )

45
[12 15 18]
[ 6 15 24]


In [12]:
# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [13]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. 
    First, for each subway station, calculate the
    mean ridership per day. 
    Then, out of all the subway stations, 
    return the maximum and minimum of these values. 
    That is, find the maximum mean-ridership-per-day and 
    the minimum mean-ridership-per-day for any subway station.
    '''
    
    mean_each_day = ridership.mean(axis = 0)
    print(mean_each_day)
    
    
    max_daily_ridership = mean_each_day.max()     # Replace this with your code
    min_daily_ridership = mean_each_day.min()     # Replace this with your code
    
    return (max_daily_ridership, min_daily_ridership)

In [14]:
min_and_max_riders_per_day(ridership)

[ 1071.2  2814.9  2718.8  3239.9  1868.2]


(3239.9000000000001, 1071.2)

## data type

In [15]:
ridership.dtype

dtype('int64')

In [16]:
enrollments = np.array([
    ['account_key', 'status', 'join_date', 'days_to_cancel', 'is_udacity'],
    [448, 'canceled', '2014-11-10', 65, True],
    [448, 'canceled', '2014-11-05', 5, True]
])

In [17]:
#the integer and boolean are converted to String
enrollments

array([['account_key', 'status', 'join_date', 'days_to_cancel',
        'is_udacity'],
       ['448', 'canceled', '2014-11-10', '65', 'True'],
       ['448', 'canceled', '2014-11-05', '5', 'True']],
      dtype='<U14')

In [18]:
#error
enrollments[:,3].mean()

TypeError: cannot perform reduce with flexible type

In [30]:
import pandas as pd

In [ ]:
enrollments = pd.DataFrame({
    'account_key':[448, 448],
    'status':['canceled', 'canceled'],
    'join_date':['2014-11-10', '2014-11-05'],
    'days_to_cancel':[65, 5],
    'is_udacity':[True, True]
}
)

In [ ]:
enrollments

In [ ]:
enrollments.mean()

In [ ]:
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [ ]:
ridership_df

In [ ]:
print( ridership_df.iloc[0])
print( ridership_df.loc['05-05-11'])
print( ridership_df['R003'])
print( ridership_df.iloc[1, 3])

In [ ]:
print( ridership_df.iloc[1:4] )

In [ ]:
print( ridership_df[['R003', 'R005']])

In [ ]:
df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print(df_1)

In [ ]:
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
print(df_2)

In [ ]:
df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print( df.sum() )
print(  df.sum(axis=1))
print(  df.values.sum())

In [ ]:
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [ ]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    overall_mean = ridership.values.mean() # Replace this with your code
    
    max_firstday = ridership.iloc[0].idxmax()#ridership_df.max(axis=1)
    print(max_firstday)
    data_max_station = ridership[max_firstday]
    print(data_max_station)
    mean_for_max = data_max_station.values.mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [ ]:
mean_riders_for_max_station(ridership_df)

In [ ]:
ridership = pd.DataFrame(
    {0: [5, 5, 5],
     1: [10, 10, 10],
     2: [15, 15, 15],
     3: [20, 20, 20],
     4: [25, 25, 25]},
    index=[0, 1, 2]
)

In [ ]:
mean_riders_for_max_station(ridership)

## load data to DataFrame

In [ ]:
subway_df = pd.read_csv('nyc-subway-weather.csv')

In [ ]:
subway_df

In [ ]:
subway_df.head() #only read some of the data

In [ ]:
subway_df.describe()

## Calculating Correlation (Pearson's r)

x1 y1 <--both above mean? both below? one above and one below?    
x2 y2 <-- ...    
x3 y3 <-- ...    
.   .     
.   .    
.   .    

Pearson's r : ranges from -1 to +1    
- First standardize each variable    
- Multiply each pair of values, and     
- take the average    
- r = average of (x in std units) * (y in std units)    

resources:    
pearson:  http://onlinestatbook.com/2/describing_bivariate_data/pearson.html    
statistics: http://onlinestatbook.com/2/index.html

Pearson's r in NumPy:https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html


In [31]:
filename = 'nyc-subway-weather.csv'
subway_df = pd.read_csv(filename)

In [32]:
subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0            0.0  2011-05-01 00:00:00     0         6     ...           30.22   
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5         0.0         30.258      55.98       7.86   
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [33]:
def correlation(x, y):
    '''
    Fill in this function to compute the correlation between the two
    input variables. Each input is either a NumPy array or a Pandas
    Series.
    
    correlation = average of (x in standard units) times (y in standard units)
    
    Remember to pass the argument "ddof=0" to the Pandas std() function!
    '''
    
    mean_x = x.mean()
    mean_y = y.mean()
    #print(mean_x)
    #print(mean_y)
     
    # By default, Pandas' std() function computes the standard deviation using Bessel's correction. 
    # Calling std(ddof=0) ensures that Bessel's correction will not be used.
    std_x = x.std(ddof=0)
    std_y = y.std(ddof=0)
    #print(std_x)
    #print(std_y)
    
    #standardize each variable
    #print(x)
    x = (x - mean_x)/std_x
    #print(x)
    y = (y - mean_y)/std_y
    
    #Multiply each pair of values, and take the average
    return (x*y).mean()

In [34]:
entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

print( correlation(entries, rain))
print( correlation(entries, temp))
print( correlation(rain, temp))

print( correlation(entries, cum_entries))



0.03564851577223041
-0.026693348321569912
-0.22903432340833663
0.5858954707662182


In [35]:
import numpy as np
np.corrcoef(entries,cum_entries)

array([[ 1.        ,  0.58589547],
       [ 0.58589547,  1.        ]])

## Pandas Axis Names

In [ ]:
# Instead of axis=0 or axis=1, you can use axis='index' or axis = 'columns'

## DataFrame Vectorized Operations

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]})
print( df1 + df2 )

In [ ]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'d': [10, 20, 30], 'c': [40, 50, 60], 'b': [70, 80, 90]})
print( df1 + df2 )

In [ ]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                       index=['row1', 'row2', 'row3'])
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                       index=['row4', 'row3', 'row2'])
print( df1 )
print( df2 )
print( df1 + df2 )

In [ ]:
# Cumulative entries and exits for one station for a few hours.
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})

In [ ]:
entries_and_exits

In [ ]:
def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
    '''
    #entries_and_exits_diff = entries_and_exits['ENTRIESn'] - entries_and_exits['EXITSn']

    #print(entries_and_exits_diff)
    #entries_and_exits_diff = entries_and_exits_diff.shift( 1) #2056161
    #entries_and_exits_diff.fillna(0,inplace=True)
    #print(entries_and_exits_diff)
    #entries_and_exits['ENTRIESn'] = entries_and_exits['ENTRIESn'] - entries_and_exits_diff
    #print(entries_and_exits)
    
    diff = entries_and_exits.shift(1)
    #diff.fillna(0,inplace=True)
    #print(diff)
    
    #print(entries_and_exits - diff)
    return (entries_and_exits - diff)
    #return entries_and_exits.diff()

In [ ]:
print(get_hourly_entries_and_exits(entries_and_exits))

## Non-Built-In Functions for DataFrames

In [ ]:
#df.applymap(clean_sate)

df = pd.DataFrame({
        'a': [1, 2, 3],
        'b': [10, 20, 30],
        'c': [5, 10, 15]
    })

In [ ]:
df

In [ ]:
def add_one(x):
    return x + 1

In [ ]:
print(df.applymap(add_one))

In [ ]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

In [ ]:
grades_df

In [ ]:
def convert_grade(grade):
    if grade >= 90:
        return 'A'
    elif grade >= 80:
        return 'B'
    elif grade >= 70:
        return 'C'
    elif grade >= 60:
        return 'D'
    else:
        return 'F'

In [ ]:
def convert_grades(grades):
    '''
    Fill in this function to convert the given DataFrame of numerical
    grades to letter grades. Return a new DataFrame with the converted
    grade.
    
    The conversion rule is:
        90-100 -> A
        80-89  -> B
        70-79  -> C
        60-69  -> D
        0-59   -> F
    '''
    return grades.applymap(convert_grade)

In [ ]:
convert_grades(grades_df)

In [ ]:
grades_df

## apply()

In [ ]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

In [ ]:
grades_df

In [ ]:
def convert_grades_curve(exam_grades):
        # Pandas has a bult-in function that will perform this calculation
        # This will give the bottom 0% to 10% of students the grade 'F',
        # 10% to 20% the grade 'D', and so on. You can read more about
        # the qcut() function here:
        # http://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html
        return pd.qcut(exam_grades,
                       [0, 0.1, 0.2, 0.5, 0.8, 1],
                       labels=['F', 'D', 'C', 'B', 'A'])

In [ ]:
    # qcut() operates on a list, array, or Series. This is the
    # result of running the function on a single column of the
    # DataFrame.
    print( convert_grades_curve(grades_df['exam1']))
    
    # qcut() does not work on DataFrames, but we can use apply()
    # to call the function on each column separately
    print( grades_df.apply(convert_grades_curve))

In [ ]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

In [ ]:
grades_df

In [ ]:
# Note that the type of standard deviation calculated by default is different between numpy's .std() and pandas' .std() functions. 
# By default, numpy calculates a population standard deviation, with "ddof = 0". 
# On the other hand, pandas calculates a sample standard deviation, with "ddof = 1". 
# If we know all of the scores, then we have a population - so to standardize using pandas, we need to set "ddof = 0".

def standardize_one_column(data):
    mean = data.mean()
    return (data-mean)/data.std(ddof = 0)

In [ ]:
def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    '''
    
    return df.apply(standardize_one_column)

In [ ]:
print(standardize(grades_df))

In [ ]:
grades_df.max()

In [ ]:
def practise_apply_max(data):
    return data.max()

In [ ]:
def practise_apply_max_(datas):
    return datas.apply(practise_apply_max)

In [ ]:
print(practise_apply_max_(grades_df))

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'a': [5, 4, 3, 1, 5],
    'b': [20, 10, 40, 50, 30],
    'c': [25, 20, 5, 15, 10]
})

In [ ]:
df

In [ ]:
print( df.apply(np.mean) )
print( df.apply(np.max) )

In [ ]:
def second_largest_inside(data):#there is a bug.
    maxi = data.max()
    second = 0
    for data_point in data:
        if data_point < maxi and data_point> second:
            second = data_point
    return second
    

In [ ]:
def second_largest(data):
    return data.apply(second_largest_inside)

In [ ]:
print(second_largest(df))

In [ ]:
#solution by instructor
def second_largest_column(data):
    sorted_values = data.sort_values(ascending = False)
    #print(sorted_values)
    return sorted_values.iloc[1]

In [ ]:
df

In [ ]:
second_largest_column(df['a'])

In [ ]:
def second_largest(data):
    return data.apply(second_largest_column)

In [ ]:
print(second_largest(df))

## Adding a DataFrame to a Series

In [ ]:
# DataFrame + DataFrame = DataFrame
# Series + Series = Series
# DataFrame + Series = ?


In [ ]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
        0: [10, 20, 30, 40],
        1: [50, 60, 70, 80],
        2: [90, 100, 110, 120],
        3: [130, 140, 150, 160]
    })

In [ ]:
s

In [ ]:
df

In [ ]:
df + s

In [ ]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10], 1: [20], 2: [30], 3: [40]})

In [ ]:
s

In [ ]:
df

In [ ]:
df + s

In [ ]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10, 20, 30, 40]})

In [ ]:
s

In [ ]:
df

In [ ]:
df + s

In [ ]:
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
df = pd.DataFrame({
        'a': [10, 20, 30, 40],
        'b': [50, 60, 70, 80],
        'c': [90, 100, 110, 120],
        'd': [130, 140, 150, 160]
    })

In [ ]:
s

In [ ]:
df

In [ ]:
df + s

In [ ]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
        'a': [10, 20, 30, 40],
        'b': [50, 60, 70, 80],
        'c': [90, 100, 110, 120],
        'd': [130, 140, 150, 160]
    })

In [ ]:
s

In [ ]:
df

In [ ]:
df + s

## Standardizing each column again

In [ ]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
        0: [10, 20, 30, 40],
        1: [50, 60, 70, 80],
        2: [90, 100, 110, 120],
        3: [130, 140, 150, 160]
    })

In [ ]:
df + s

In [ ]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
        0: [10, 20, 30, 40],
        1: [50, 60, 70, 80],
        2: [90, 100, 110, 120],
        3: [130, 140, 150, 160]
    })

In [19]:
df.add(s, axis='index')

NameError: name 'df' is not defined

In [20]:
df.add(s, axis='columns')

NameError: name 'df' is not defined

In [ ]:
s

In [ ]:
df

In [ ]:
df.divide(s, axis='index')

In [ ]:
df.divide(s)

In [ ]:
# # The functions sub(), mul(), and div() work similarly to add()

df.subtract(s, axis='index')

In [ ]:
df.mul(s, axis='index')

In [ ]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

In [ ]:
grades_df

In [ ]:
# ddof = 0
def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    
    This time, try to use vectorized operations instead of apply().
    You should get the same results as you did before.
    '''
    mean = df.mean()
    std = df.std(ddof = 0)
    print(mean)
    print(std)
    
    df = df.sub(mean, axis='columns')
    df = df.div(std, axis='columns')
    return df

In [ ]:
def standardize_rows(df):
    '''
    Optional: Fill in this function to standardize each row of the given
    DataFrame. Again, try not to use apply().
    
    This one is more challenging than standardizing each column!
    '''
    mean = df.mean(axis='columns')
    std = df.std(ddof = 0,axis='columns')
    print(mean)
    print(std)
    
    
    df = df.sub(mean, axis='index')
    df = df.div(std, axis='index')
    
    return df

In [ ]:
df

In [ ]:
print(df.mean(axis='columns'))
print(df.std(ddof=0,axis='columns'))

In [ ]:
standardize(grades_df)

In [ ]:
standardize_rows(grades_df)

In [ ]:
df = pd.DataFrame(
    {0: [95, 85, 75, 65, 55], 1: [94, 84, 74, 64, 54]},
    index=[0, 1, 2, 3, 4]
)

In [ ]:
df

In [ ]:
standardize_rows(df)

## pandas groupby()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
values = np.array([1, 3, 2, 4, 1, 6, 4])
example_df = pd.DataFrame({
    'value': values,
    'even': values % 2 == 0,
    'above_three': values > 3 
}, index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])


In [ ]:
values

In [ ]:
example_df

In [ ]:
grouped_data = example_df.groupby('even')

In [ ]:
grouped_data.groups

In [ ]:
grouped_data = example_df.groupby(['even', 'above_three'])

In [ ]:
grouped_data.groups

In [ ]:
grouped_data = example_df.groupby('even')

In [ ]:
example_df

In [ ]:
grouped_data.sum()

In [ ]:
grouped_data.sum()['value']

In [ ]:
grouped_data['value'].sum()

In [ ]:
filename = 'nyc-subway-weather.csv'
subway_df = pd.read_csv(filename)

In [ ]:
subway_df.head()

In [ ]:
### Write code here to group the subway data by a variable of your choice, then
### either print out the mean ridership within each group or create a plot.
grouped_subway = subway_df.groupby('day_week')

In [ ]:
grouped_subway.groups

In [ ]:
ridership_by_day = grouped_subway['ENTRIESn_hourly'].mean()

In [ ]:
%pylab inline
import seaborn as sns
ridership_by_day.plot()

In [ ]:
rain_by_day = grouped_subway['rain'].mean()


In [ ]:
%pylab inline
import seaborn as sns
rain_by_day.plot()

In [ ]:
grouped_subway = subway_df.groupby('TIMEn')
ridership_by_time = grouped_subway['ENTRIESn_hourly'].mean()

In [ ]:
%pylab inline
import seaborn as sns
ridership_by_time.plot()

## Using groupby() to Calculate Hourly Entries and Exits

In [ ]:
'''
In the quiz where you calculated hourly entries and exits, you did so for a single set of cumulative entries. 

However, in the original data, there was a separate set of numbers for each station.

Thus, to correctly calculate the hourly entries and exits, 
it was necessary to group by station and day, then calculate the hourly entries and exits within each day.

Write a function to do that. 
You should use the apply() function to call the function you wrote previously. 
You should also make sure you restrict your grouped data to just the entries and exits columns, 
since your function may cause an error if it is called on non-numerical data types.

If you would like to learn more about using groupby() in Pandas, this page contains more details.http://pandas.pydata.org/pandas-docs/stable/groupby.html

Note: You will not be able to reproduce the ENTRIESn_hourly and EXITSn_hourly columns in the full dataset 
using this method. When creating the dataset, we did extra processing to remove erroneous values.


To clarify the structure of the data, the original data recorded the cumulative number of entries on each station at four-hour intervals. 
For the quiz, you just need to look at the differences between consecutive measurements on each station: 
by computing "hourly entries", 
we just mean recording the number of new tallies between each recording period as a contrast to "cumulative entries".

'''

subway_df.head()

In [ ]:
values = np.array([1, 3, 2, 4, 1, 6, 4])
example_df = pd.DataFrame({
    'value': values,
    'even': values % 2 == 0,
    'above_three': values > 3 
}, index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])


In [ ]:
example_df

In [ ]:
def standardize(xs):
    return (xs - xs.mean()) / xs.std()

In [ ]:
grouped_data = example_df.groupby('even')
print(grouped_data.groups)

In [ ]:
grouped_data['value'].mean()

In [ ]:
grouped_data['value'].std()

In [ ]:
grouped_data['value'].apply(standardize)

In [ ]:
def second_largest(xs):
    sorted_xs = xs.sort_values(inplace=False, ascending=False)
    return sorted_xs.iloc[1]

In [ ]:
grouped_data = example_df.groupby('even')

In [ ]:
grouped_data['value'].apply(second_largest)

In [ ]:
#QUIZ

In [ ]:
ridership_df = pd.DataFrame({
    'UNIT': ['R051', 'R079', 'R051', 'R079', 'R051', 'R079', 'R051', 'R079', 'R051'],
    'TIMEn': ['00:00:00', '02:00:00', '04:00:00', '06:00:00', '08:00:00', '10:00:00', '12:00:00', '14:00:00', '16:00:00'],
    'ENTRIESn': [3144312, 8936644, 3144335, 8936658, 3144353, 8936687, 3144424, 8936819, 3144594],
    'EXITSn': [1088151, 13755385,  1088159, 13755393,  1088177, 13755598, 1088231, 13756191,  1088275]
})

In [ ]:
ridership_df

In [ ]:
def get_hourly_entry_and_exit(entries_and_exits):
    diff = entries_and_exits.shift(1)
    return (entries_and_exits - diff)

In [ ]:
def get_hourly_entries_and_exits(entries_and_exits):
    grouped_data = entries_and_exits.groupby('UNIT')
    return grouped_data['ENTRIESn','EXITSn'].apply(get_hourly_entry_and_exit)

In [ ]:
get_hourly_entries_and_exits(ridership_df)

In [ ]:
entries_and_exits = pd.DataFrame(
    {'ENTRIESn': [10, 40, 60, 65, 85],
     'EXITSn': [0, 10, 20, 60, 60],
     'UNIT': ['R001', 'R001', 'R001', 'R001', 'R001']},
    index=[0, 1, 2, 3, 4]
)

In [ ]:
get_hourly_entries_and_exits(entries_and_exits)

## Combining Pandas DataFrames

In [ ]:
#how = 'left'
#how = 'inner
#merge

In [ ]:
entries_and_exits = pd.DataFrame(
    {'ENTRIESn': [10, 40, 60, 65, 85],
     'EXITSn': [0, 10, 20, 60, 60],
     'UNIT': ['R001', 'R001', 'R001', 'R001', 'R001']},
    index=[0, 1, 2, 3, 4]
)

In [ ]:
grouped_data = entries_and_exits.groupby('UNIT')

In [ ]:
entries = grouped_data['ENTRIESn'].apply(get_hourly_entry_and_exit)

In [ ]:
exits = grouped_data['EXITSn'].apply(get_hourly_entry_and_exit)

In [ ]:
entries = pd.DataFrame(entries)
entries

In [ ]:
exits = pd.DataFrame(exits)
exits

In [ ]:
entries.merge(exits, how='inner')

In [ ]:
enrollments1 = pd.DataFrame({
    'account_key':[447, 448, 448],
    'days_to_cancel':[100,65, 5],
    'status':['current', 'current', 'canceled'],
    'join_date':['2014-11-07','2014-11-10', '2014-11-05']
}
)

In [ ]:
enrollments2 = pd.DataFrame({
    'account_key':[448, 448, 449],
    'days_to_cancel':[65, 5, 9],
    'is_udacity':[True, False, False]
}
)

In [ ]:
enrollments2

In [ ]:
enrollments1

In [ ]:
enrollments2.merge(enrollments1, on=['account_key'])#product

In [ ]:
enrollments2.merge(enrollments1, on=['account_key','days_to_cancel'])#product

In [ ]:
enrollments2.merge(enrollments1, on='account_key', how='left')

In [ ]:
enrollments2.merge(enrollments1, on='account_key', how='right')

In [ ]:
enrollments2.merge(enrollments1, on='account_key', how='inner')

In [ ]:
enrollments2.merge(enrollments1, on='account_key', how='outer')

In [ ]:
enrollments2.merge(enrollments1)

In [ ]:
subway_df = pd.DataFrame({
    'UNIT': ['R003', 'R003', 'R003', 'R003', 'R003', 'R004', 'R004', 'R004',
             'R004', 'R004'],
    'DATEn': ['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
              '05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11'],
    'hour': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'ENTRIESn': [ 4388333,  4388348,  4389885,  4391507,  4393043, 14656120,
                 14656174, 14660126, 14664247, 14668301],
    'EXITSn': [ 2911002,  2911036,  2912127,  2913223,  2914284, 14451774,
               14451851, 14454734, 14457780, 14460818],
    'latitude': [ 40.689945,  40.689945,  40.689945,  40.689945,  40.689945,
                  40.69132 ,  40.69132 ,  40.69132 ,  40.69132 ,  40.69132 ],
    'longitude': [-73.872564, -73.872564, -73.872564, -73.872564, -73.872564,
                  -73.867135, -73.867135, -73.867135, -73.867135, -73.867135]
})

In [ ]:
weather_df = pd.DataFrame({
    'DATEn': ['05-01-11', '05-01-11', '05-02-11', '05-02-11', '05-03-11',
              '05-03-11', '05-04-11', '05-04-11', '05-05-11', '05-05-11'],
    'hour': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'latitude': [ 40.689945,  40.69132 ,  40.689945,  40.69132 ,  40.689945,
                  40.69132 ,  40.689945,  40.69132 ,  40.689945,  40.69132 ],
    'longitude': [-73.872564, -73.867135, -73.872564, -73.867135, -73.872564,
                  -73.867135, -73.872564, -73.867135, -73.872564, -73.867135],
    'pressurei': [ 30.24,  30.24,  30.32,  30.32,  30.14,  30.14,  29.98,  29.98,
                   30.01,  30.01],
    'fog': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'rain': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'tempi': [ 52. ,  52. ,  48.9,  48.9,  54. ,  54. ,  57.2,  57.2,  48.9,  48.9],
    'wspdi': [  8.1,   8.1,   6.9,   6.9,   3.5,   3.5,  15. ,  15. ,  15. ,  15. ]
})

In [ ]:
weather_df

In [ ]:
subway_df

In [ ]:
def combine_dfs(subway_df, weather_df):
    '''
    Fill in this function to take 2 DataFrames, one with subway data and one with weather data, and 
    return a single dataframe with one row for each date, hour, and location. 
    Only include times and locations that have both subway data and weather data available.
    '''
    
    
    return subway_df.merge(weather_df, on = ['DATEn','hour','latitude','longitude'], how = 'inner')

In [ ]:
print(combine_dfs(subway_df, weather_df))

In [ ]:
weather_df = pd.DataFrame({
    'date': ['05-01-11', '05-01-11', '05-02-11', '05-02-11', '05-03-11',
              '05-03-11', '05-04-11', '05-04-11', '05-05-11', '05-05-11'],
    'hour': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'latitude': [ 40.689945,  40.69132 ,  40.689945,  40.69132 ,  40.689945,
                  40.69132 ,  40.689945,  40.69132 ,  40.689945,  40.69132 ],
    'longitude': [-73.872564, -73.867135, -73.872564, -73.867135, -73.872564,
                  -73.867135, -73.872564, -73.867135, -73.872564, -73.867135],
    'pressurei': [ 30.24,  30.24,  30.32,  30.32,  30.14,  30.14,  29.98,  29.98,
                   30.01,  30.01],
    'fog': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'rain': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'tempi': [ 52. ,  52. ,  48.9,  48.9,  54. ,  54. ,  57.2,  57.2,  48.9,  48.9],
    'wspdi': [  8.1,   8.1,   6.9,   6.9,   3.5,   3.5,  15. ,  15. ,  15. ,  15. ]
})

In [ ]:
subway_weather_df = subway_df.merge(weather_df, 
                left_on = ['DATEn','hour','latitude','longitude'], 
                right_on = ['date','hour','latitude','longitude'] ,
                how = 'inner')

## Plotting with DataFrames

In [ ]:
subway_weather_df.plot()

In [ ]:
# for more complicated plots you will usually want to use matplotlib directly
# https://matplotlib.org/api/pyplot_api.html

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
values = np.array([1, 3, 2, 4, 1, 6, 4])
example_df = pd.DataFrame({
    'value': values,
    'even': values % 2 == 0,
    'above_three': values > 3 
}, index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])


In [ ]:
example_df

In [ ]:
first_even = example_df.groupby('even').first()

In [ ]:
first_even

In [ ]:
first_even['even'] # Causes an error. 'even' is no longer a column in the DataFrame

In [ ]:
first_even = example_df.groupby('even', as_index=False).first()

In [ ]:
first_even

In [ ]:
first_even['even'] # Now 'even' is still a column in the DataFrame

In [ ]:
filename = 'nyc-subway-weather.csv'
subway_df = pd.read_csv(filename)

In [ ]:
subway_df.head()

In [ ]:
## Make a plot of your choice here showing something interesting about the subway data.
## Matplotlib documentation here: http://matplotlib.org/api/pyplot_api.html
## Once you've got something you're happy with, share it on the forums!
grouped_data = subway_df.groupby('UNIT',as_index=False).first()


In [21]:
#grouped_data['UNIT','ENTRIESn'].plot()#scatter  grouped_data['ENTRIESn','EXITSn']

In [22]:
plt.scatter(grouped_data['UNIT'],grouped_data['ENTRIESn_hourly'])

NameError: name 'plt' is not defined

In [23]:
grouped_data = subway_df.groupby('tempi',as_index=False).first()
plt.scatter(grouped_data['tempi'],grouped_data['ENTRIESn'])

NameError: name 'subway_df' is not defined

In [24]:
%pylab inline
import seaborn as sns

grouped_data = subway_df.groupby('rain')
grouped_data.head()

Populating the interactive namespace from numpy and matplotlib


NameError: name 'subway_df' is not defined

In [ ]:
data_by_location = subway_df.groupby(['latitude','longitude'], as_index = False ).mean()
data_by_location.head()

In [ ]:
scaled_entries = data_by_location['EXITSn_hourly']/data_by_location['EXITSn_hourly'].std()

In [ ]:
%pylab inline
plt.scatter(data_by_location['latitude'], data_by_location['longitude'],s= scaled_entries)

In [ ]:
#Histograms of subway ridership on both days with rain and days without rain
data_by_rain = subway_df.groupby(['rain','DATEn'], as_index = False ).mean()
data_by_rain.head()


In [ ]:
%pylab inline
plt.scatter(data_by_rain['DATEn'], data_by_rain['ENTRIESn'],c = data_by_rain['rain'])

In [ ]:
data_rain = data_by_rain.loc[data_by_rain['rain'] ==0,['DATEn','ENTRIESn_hourly']]
#print(data_by_rain.head())
print(data_rain.head())

In [ ]:
data_no_rain = data_by_rain.loc[data_by_rain['rain'] ==1,['DATEn','ENTRIESn_hourly']]
data_no_rain.head()

In [ ]:
%pylab inline
plt.hist(data_rain['ENTRIESn_hourly'])
plt.hist(data_no_rain['ENTRIESn_hourly'])

In [ ]:
%pylab inline
plt.scatter(data_rain['DATEn'],data_rain['ENTRIESn_hourly'])
plt.scatter(data_no_rain['DATEn'],data_no_rain['ENTRIESn_hourly'])

## Three-Dimensional Data

In [ ]:
#3D data in NumPy
#NumPy arrays can have arbitrarily many dimensions. 
a = np.array([
    [['A1A','A2A','A3A'],['A1B','A2B','A3B']],
    [['B1A','B2A','B3A'],['B1B','B2B','B3B']],
]
)

In [ ]:
a

In [ ]:
a[0][0][0]

In [ ]:
# 3D data in Pandas
#Panda has a data structure called a Panel, which is similar to a DataFrame or a Seriews, but for 3D data.
# http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel

In [ ]:
#more links
#Red pandas playing in the snow  https://www.youtube.com/watch?v=DSehQsYU9h4
#Giant panda puts baby panda to bed http://www.dailymail.co.uk/video/news/video-1085584/TOO-CUTE-Giant-Panda-puts-Baby-Panda-bed-Taipei-Zoo.html
#Pandas playing on a slide  https://www.youtube.com/watch?v=sGF6bOi1NfA